name: Color Collector
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "53 14 * * *"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  pipeline:
    name: Pipeline
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo " start at"
          echo $PWD
      - uses: actions/checkout@v4
      - name: Install Python3
        shell: bash
        run: |
          sudo apt-get install -y python3 python3-dev python3-venv python3-pip python3-docutils
          python3 -m pip install --user -r requirements.txt
      - name: Install Google-Chrome
        shell: bash
        run: |
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          echo 'which google-chrome'
          which google-chrome
          echo 'google-chrome --version'
          google-chrome --version
      - uses:
          nanasess/setup-chromedriver@v2
          # with:
          # Optional: do not specify to match Chrome's version
          # chromedriver-version: '88.0.4324.96'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Collect Colors
        shell: bash
        run: |
          export PYTHONPATH="$PWD:$PYTHONPATH"
          python3 collect.py
      - name: Auto Commit
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(colors): auto update colorschemes list"
